version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample site from https://startbootstrap.com/template-overviews/agency/
#İlk başta nginx-customı bulmaya çalışacaktır, bulamayacak ve bu yüzden build çalışacak
#ikinci kez çalışsa buil komutları çalışmayacaktır
# ama illada build yapsın istersek "docker-compose up --build" komutu çalıştırılabilir
services:
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx-custom
    ports:
      - '80:80'
  web:
    image: httpd
    volumes:
      - ./html:/usr/local/apache2/htdocs/